### ISSUE TITLE
Octree to Octree comparison volume information does not stay on screen

### ISSUE THREAD

**Issue by rarrais** [miguelriemoliveira/octomap_tools#1]
Volume information just appears on screen for a brief period of time.

**Comment by miguelriemoliveira** [comment]
Hello Rafael,

Did you try changing the lifetime field of the markers that disappear quickly? 

Regards,

Miguel

**Comment by rarrais** [comment]
Project has changed to the https://github.com/rarrais/STAMINA-ASCD repository.

Check https://github.com/rarrais/STAMINA-ASCD/issues/5 for this issue.
