### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by joao-pm-santos96** [miguelriemoliveira/octomap_tools#3]
Hi @miguelriemoliveira . Fixed the memory leak like we talked, yet I have another problem. In [test_unknown_space](https://github.com/miguelriemoliveira/octomap_tools/blob/master/world_model_consistency_check/src/test_unknown_space.cpp) if I use the default 0.15 resolution everything works fine. Yet, if I use 0.05 resolution, my rviz completely freezes... any improvement suggestion regarding this problem?

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 , when you say resolution you mean the octomap resolution?
Or the resolution of the search for unkown cells?
Which node eats up more processing and memory? Octomap_server? FindUnknownSpace?

**Comment by joao-pm-santos96** [comment]
I mean the resolution of the search for unknown cells. When I run my launch file every process has the name “rviz” so it’s hard to distuinguish. Yet it’s only when I run find unknown space with 0.05 resolution that the problem shows.  If I run it with the default 0.15 or don’t run it at all, there is no FPS drops

**Comment by joao-pm-santos96** [comment]
But the memory doesn’t seam to be the problem anymore since it stays stable at a value not too much full (a little less of 5gb in a laptop with 8gb total ram if I remember correctly)

**Comment by miguelriemoliveira** [comment]
Hi,

1. Its strange that all your processes are called rviz ...

2. Although the memory leak is solved, it is a lot for a process to take
5gb of ram.

3. One way to optimize i can think of is to give memory to the find unknown
space node. Assume you have to search 5 positions. The initial state will
be all 5 unknown : U U U U U. After the first iteration, lets say 3 cells
are occupied or free (thus known), so now we have: K K U U K. The second
iteration needs not to search all five positions, but only the two
remaining unknown positions.

4. Another way would be to paralelize the search of unknown cells, we may
discuss this afterwards.

Keep up the good work!




A Qua, 3/04/2019, 23:24, João Santos <notifications@github.com> escreveu:

**Comment by joao-pm-santos96** [comment]
Hello professor,

Exactly I thought that to, even if I don't include rviz in the launh file, the hogging only start when it is launched and all the processes are called "rviz" (Update: today this doesn't seams to happen...) 

I explained my self wrong, it's not one process that uses 5gb of ram, what I meant was that the whole system has 5gb full, I'll put a screenshot bellow.

Really liked that ideia, it's one possibility. Another one is to search how the octomar server itself caracterizes the free and occupied cells and try to implement that for the unknown ones. This point (nr 3) will be my focus today.

Palatalization sounds good but actually I don't know if it will make a difference because the cpu (4 cores 8 threads) are already pretty busy, like in the htop screenshot bellow: 

With test unknown space running: 
![Screenshot from 2019-04-04 09-24-09](https://user-images.githubusercontent.com/47630528/55541114-3d12e680-56bc-11e9-85c7-49180d9cab40.png)

Without test unknown space running: 
![Screenshot from 2019-04-04 09-25-28](https://user-images.githubusercontent.com/47630528/55541135-47cd7b80-56bc-11e9-8d2d-77ae4e5076a2.png)

**Comment by joao-pm-santos96** [comment]
Using octomap_binary instead of octomap_full shows no improvement

**Comment by joao-pm-santos96** [comment]
Well here is what I tried until this moment: instead of using 3 nested for loops, I used the octomap function getUnknownLeafCenters (in the end does more or less the same thing actually...) and published the CUBE_LIST almost exactly as octomap_server does. It improved a little bit, but nothing major.. Today I adapted once again the code so instead of publishing markers, it published the PointCLoud2 corresponding to the unknown centers. It is much faster! So my guess is that the problem is not in getting the unknown voxels but actually somewhere in the processing of the markers

**Comment by joao-pm-santos96** [comment]
The code: 

void octomapCallback(const octomap_msgs::Octomap::ConstPtr &msg)
{
    if (octree != NULL)
    {
        // ROS_INFO("DEBUG: Going to DEL OCTREE");
        delete (octree);
        // ROS_INFO("DEBUG: Octree DEL");
    }

    tree = msgToMap(*msg);
    octree = dynamic_cast<OcTree *>(tree);

    string frame_id = "/base_link";

    point3d min;
    min.x() = -0.5;
    min.y() = -0.5;
    min.z() = -0.5;

    point3d max;
    max.x() = 0.5;
    max.y() = 0.5;
    max.z() = 0.5;

    ros::param::get("~min_x", min.x());
    ros::param::get("~min_y", min.y());
    ros::param::get("~min_z", min.z());

    ros::param::get("~max_x", max.x());
    ros::param::get("~max_y", max.y());
    ros::param::get("~max_z", max.z());

    //ros::param::get("~resolution", resolution);
    ros::param::get("~fixed_frame", frame_id);

    int treeDepth = octree->getTreeDepth();
    visualization_msgs::MarkerArray unknownNodes;

    // unknownNodes.markers.resize(treeDepth + 1);

    point3d_list unknown_centers;
    pcl::PointCloud<pcl::PointXYZRGBA> unknownPC;

    octree->getUnknownLeafCenters(unknown_centers, min, max, 0);

    double resolution = octree->getResolution();

    int num_of_unknown_cells = unknown_centers.size();
    unknownNodes.markers.resize(num_of_unknown_cells);

    ROS_INFO("Total unknown centers: %d", num_of_unknown_cells);

    int id = 0;
    ros::Time t = ros::Time::now();

    for (point3d_list::iterator it = unknown_centers.begin(); it != unknown_centers.end(); ++it)
    {
        geometry_msgs::Point cubeCenter;
        cubeCenter.x = it->octomath::Vector3::x();
        cubeCenter.y = it->octomath::Vector3::y();
        cubeCenter.z = it->octomath::Vector3::z();
        unknownNodes.markers[id].points.push_back(cubeCenter);
        id++;

        pcl::PointXYZRGBA unknown_leaf_center_point;
        unknown_leaf_center_point.x = it->octomath::Vector3::x();
        unknown_leaf_center_point.y = it->octomath::Vector3::y();
        unknown_leaf_center_point.z = it->octomath::Vector3::z();
        unknown_leaf_center_point.r = 1.0 * 255;
        unknown_leaf_center_point.g = 0.6 * 255;
        unknown_leaf_center_point.b = 0.0 * 255;
        unknown_leaf_center_point.a = 1.0 * 255;
        unknownPC.push_back(unknown_leaf_center_point);
    }
    sensor_msgs::PointCloud2 cloud;
    pcl::toROSMsg(unknownPC, cloud);
    cloud.header.frame_id = frame_id;
    cloud.header.stamp = t;
    cloud_pub.publish(cloud);

    ROS_INFO("Points centers added: %d", id);
    id = 0;
    
    for (point3d_list::iterator it = unknown_centers.begin(); it != unknown_centers.end(); ++it)
    {

        unknownNodes.markers[id].ns = "boxes";
        unknownNodes.markers[id].header.frame_id = frame_id;
        unknownNodes.markers[id].header.stamp = t;
        // unknownNodes.markers[id].action = visualization_msgs::Marker::ADD;
        unknownNodes.markers[id].id = id;
        unknownNodes.markers[id].type = visualization_msgs::Marker::CUBE_LIST;
        unknownNodes.markers[id].scale.x = resolution;
        unknownNodes.markers[id].scale.y = resolution;
        unknownNodes.markers[id].scale.z = resolution;
        unknownNodes.markers[id].color.r = 1.0;
        unknownNodes.markers[id].color.g = 0.6;
        unknownNodes.markers[id].color.b = 0.0;
        unknownNodes.markers[id].color.a = 1;

        if (unknownNodes.markers[id].points.size() > 0)
        {
            unknownNodes.markers[id].action = visualization_msgs::Marker::ADD;
        }
        else
        {
            unknownNodes.markers[id].action = visualization_msgs::Marker::DELETE;
        }

        id++;
    }

    marker_pub.publish(unknownNodes);
    ROS_INFO("Cubes created: %d", id);
}

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,

this is good news! So the problem is not computing hte unknown voxels but actually to rendereing them in rviz? 

Are we any close to real time? Can you make a demonstration on Monday's meeting?

In the meantime, don't forget to start writing the document.

Good work,
Miguel

**Comment by joao-pm-santos96** [comment]
I don't know exactly what you mean with real time but octomap_server (topics octomap_full and occupied_cells_vis_array) is publishing at ~2Hz and our node (publishing the unknown markers and the point cloud) is also at ~2Hz. It's only when opening Rviz that freezes. Maybe because my pc isn't able to run the discrete nvidia grapgics card (?). But if it was that, occupied_cells_vis_array would also freeze Rviz I think.. 

Yeah for sure, monday I'll do a demo of this, see you then!

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,

2Hz is real time! ... for turltes :)

It is fine for us I think.

**Comment by joao-pm-santos96** [comment]
So I was writing some things in the document when I got an idea: what if I used the published point cloud from the unknown centers as the cloud_in in a new octomap_server_node? Well it worked! I could visualize the new octomap (in which being occupied actually means that it is unknown in the "real world") and rviz would keep a steady ~30fps. Maybe instead of doing so in a launch file, if I do it inside our node, it becomes the possible solution? What do you think, should I invest some time in this?

**Comment by joao-pm-santos96** [comment]
And thanks for all the replies @miguelriemoliveira !!

**Comment by miguelriemoliveira** [comment]
Hello João,

I'm not sure The best way to proceed is to use octomap server as an
intermediary to plot the cubes.

It would be better if you find out how octomap server sends the cubes to
rviz and then do the same in your node.

Because having a second octomap server will surely take unecessary
processing time.

Miguel



A Sáb, 6/04/2019, 16:10, João Santos <notifications@github.com> escreveu:

**Comment by joao-pm-santos96** [comment]
Hi! 

The ideia was not to have another octomap_server running. I already publish the cubes like octomap_server, but my guess is that I'm publishing too many.

So the ideia was to create new octomap based on the unknown centers (inside our node), and with some function from octomap or some other way that I would need to investigate, reduce the number of voxels (aka cubes, because of having the same "occupied" state) and then publishing the cubes from this latter ocomap. All of this inside our node. What I expect is for them be less and have different sizes.

Maybe I can explain it better and discuss it on Monday

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,

now I understand. You want to merge the small unkown cubes into bigger ones whenever possible, thus reducing the number of published cubes. It is a good idea, lets discuss it on Monday ...

**Comment by joao-pm-santos96** [comment]
Yup, exactly! I've tested is, I think it works and solves the problem! Tomorrow morning I'll show you, see you then!

Thanks, João.

**Comment by joao-pm-santos96** [comment]
solved in octomap_boundingbox
